version: "3.7"
services:
  apache:
    build: ./apache
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    image: ${COMPOSE_PROJECT_NAME}/apache
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_EXPOSED_PORT}:80"
    volumes:
      - ../app:/app:rw,cached
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_BD=${MYSQL_BD}

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    networks:
      - backend
    volumes:
      - mysql-5.7:${MYSQL_DATA_DIR}:rw,cached
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    links:
      - mysql:db
    ports:
      - 8000:80
    networks:
      - backend
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

networks:
  frontend:
  backend:

volumes:
  mysql-5.7:
    external: true