version: "3.7"
services:
  php:
    build: ./php
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: ${COMPOSE_PROJECT_NAME}/php
    networks:
      - backend
    volumes:
      - ../app/:${CONTAINER_APP_DIR}:rw,cached
      - ../logs/php:${PHP_LOG_DIR}:rw,cached
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  apache:
    build: ./apache
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    image: ${COMPOSE_PROJECT_NAME}/apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_EXPOSED_PORT}:80"
    volumes:
      - ../app/:${CONTAINER_APP_DIR}:rw,cached
    environment:
      - CONTAINER_APP_DIR=${CONTAINER_APP_DIR}
  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    networks:
      - backend
    volumes:
      - mysql-5.7:${MYSQL_DATA_DIR}:rw,cached
      - ../logs/mysql:${MYSQL_LOG_DIR}:rw,cached

networks:
  frontend:
  backend:

volumes:
  mysql-5.7:
    external: true